import { z } from 'zod';

export const participanteSchema = z.object({
    nomeCompleto: z.string().min(5, 'O nome deve ter pelo menos 5 caracteres'),
    apelido: z.string().min(2, 'O apelido deve ter pelo menos 2 caracteres'),
    dataNascimento: z.string(),
    sexo: z.enum(['MASCULINO', 'FEMININO']),
    cpf: z.string().optional().nullable(),
    email: z.string().email('E-mail inválido'),
    telefone: z.string().min(10, 'Telefone inválido'),
    instagram: z.string().optional().nullable(),
    receberEmail: z.boolean().default(true),
    receberWhatsapp: z.boolean().default(true),
    estadoCivil: z.enum(['SOLTEIRO', 'CASADO', 'UNIAO_ESTAVEL', 'DIVORCIADO', 'VIUVO']).optional().nullable(),
    moraComQuem: z.string().optional().nullable(),
    estadoCivilPais: z.string().optional().nullable(),
    nomeMae: z.string().optional().nullable(),
    telefoneMae: z.string().optional().nullable(),
    enderecoMae: z.string().optional().nullable(),
    nomePai: z.string().optional().nullable(),
    telefonePai: z.string().optional().nullable(),
    enderecoPai: z.string().optional().nullable(),
    escolaridade: z.string(),
    instituicaoEnsino: z.string().optional().nullable(),
    profissao: z.string(),
    trabalha: z.boolean().default(false),
    localTrabalho: z.string().optional().nullable(),
    batizado: z.boolean().default(false),
    localBatismo: z.string().optional().nullable(),
    fezPrimeiraComunhao: z.boolean().default(false),
    fezCrisma: z.boolean().default(false),
    enderecoCompleto: z.string().optional().nullable(),
    bairro: z.string().optional().nullable(),
    restricoesAlimentares: z.string().optional().nullable(),
    alergias: z.string().optional().nullable(),
    problemasSaude: z.string().optional().nullable(),
    medicamentosContinuos: z.string().optional().nullable(),
    amigosParentesInscritos: z.string().optional().nullable(),
    contatosEmergencia: z.string(), // Mantido como string JSON por enquanto
    lgpdCiente: z.boolean().optional().nullable(),
    tipo: z.string().optional().nullable(),
    corGrupo: z.string().optional().nullable(),
    fotoUrl: z.string().optional().nullable(),
    comprovanteUrl: z.string().optional().nullable(),
});

export const trabalhadorSchema = z.object({
    tipoInscricao: z.enum(['SOLTEIRO', 'CASAIS_UNIAO_ESTAVEL']),
    email: z.string().email('E-mail inválido'),
    nomeCompleto1: z.string().min(5),
    cpf1: z.string().optional().nullable(),
    contato1: z.string(),
    instagram1: z.string().optional().nullable(),
    sexo1: z.enum(['MASCULINO', 'FEMININO']),
    dataNascimento1: z.string(),

    nomeCompleto2: z.string().optional().nullable(),
    cpf2: z.string().optional().nullable(),
    contato2: z.string().optional().nullable(),
    instagram2: z.string().optional().nullable(),
    sexo2: z.enum(['MASCULINO', 'FEMININO']).optional().nullable(),
    dataNascimento2: z.string().optional().nullable(),

    receberEmail: z.boolean().default(true),
    receberWhatsapp: z.boolean().default(true),
    enderecoCompleto: z.string().optional().nullable(),
    trabalhamOuEstudam: z.boolean().default(false),
    areaTrabalhoEstudo: z.string().optional().nullable(),
    paroquiaEjcAno: z.string().optional().nullable(),
    equipesJaServiram: z.string().optional().nullable(),
    tocaInstrumento: z.boolean().default(false),
    qualInstrumento: z.string().optional().nullable(),
    sabeCantar: z.boolean().default(false),
    operaEquipamentosSom: z.boolean().default(false),
    habilidadesComputador: z.boolean().default(false),
    trabalhosManuais: z.boolean().default(false),
    apelido: z.string().optional().nullable(),
    apelido2: z.string().optional().nullable(),
    // Novos campos
    profissao1: z.string().optional().nullable(),
    profissao2: z.string().optional().nullable(),
    habilidadesTalentos: z.string().optional().nullable(),
    fotoUrl1: z.string().optional().nullable(),
    fotoUrl2: z.string().optional().nullable(),
    lgpdCiente: z.boolean().optional().nullable(),
    tipo: z.string().optional().nullable(),
});
